### ISSUE TITLE
Portal 1 Buttons missing proper collisions

### ISSUE THREAD

**Issue by Luke18033** [BEEmod/BEE2-items#1154]
The cube is clipping into the button:
![20161206132150_1](https://cloud.githubusercontent.com/assets/19228201/20944141/2d843fd6-bbb7-11e6-953a-b925684188a7.jpg)

**Comment by Jadeygaming** [comment]
But It's Just The SLIGHT, Is It Really Necessary?

**Comment by Luke18033** [comment]
It can't be that hard to fix, the actual Portal 1 didn't have this.

**Comment by Luke18033** [comment]
@Jadeygaming Also it is necessary if I noticed it *the first time* I put a cube on a button in Pr23.

**Comment by Flametusk** [comment]
I noticed it the first time I used it in 22. And yes, it is one of those things, because the cube doesn't fall with the button, so it looks weird.

**Comment by HugoBDesigner** [comment]
This bug could be easily fixed by adding a cube-only brush slightly higher than usual on the button.

**Comment by TeamSpen210** [comment]
The problem is that I don't want to block the cube from also pressing the button. This has been fixed though be using a combined animated model which moves right.

**Comment by Luke18033** [comment]
That's used in Pr24, right? In that case it's just "fixed" and not "fixed in next release".

**Comment by HugoBDesigner** [comment]
I got the most up-to-date dev version and the issue is still there

**Comment by Luke18033** [comment]
Nope.
![20170314153035_1](https://cloud.githubusercontent.com/assets/19228201/23925635/611e7e0c-08cd-11e7-8db8-5f9b90a36096.jpg)

**Comment by Luke18033** [comment]
Indeed, this in included in Pr24.
