### ISSUE TITLE
Some custom fizzlers use their Clean model for the laserfield variant in Old Aperture

### ISSUE THREAD

**Issue by Luke18033** [BEEmod/BEE2-items#3112]
The title says it all.
![image](https://user-images.githubusercontent.com/19228201/64928755-5ffc0780-d7d1-11e9-87a0-9ee2dc979fe4.png)

**Comment by LautaroL20** [comment]
I think I will going to try fixing this myself since I have a bit of experience at Blender.

**Comment by Luke18033** [comment]
There's no modeling to be done here, the laserfield variants are just set to use the wrong model. This is probably fixed by now anyway?

**Comment by LautaroL20** [comment]
This still happens with the Physics Repulsion Field. Also, seeing at the Radiative Flux Rectangle editor model which do not have that annoying blue fiel on it, would be nice if this could also be applied in the rest of the custom fizzlers so we could make custom fields for them as is the case of the RFR... but not sure if this would break the items.
