### ISSUE TITLE
Cubes passing through gratings like thin air BEEMOD 4.36.1

### ISSUE THREAD

**Issue by Venima** [BEEmod/BEE2-items#3264]
First of all, from what I've heard this is a known bug(?), and I can prevent this by using 128x128 wall gratings, however this doesn't really suit all purposes. I also noticed this happens to the vacuum of [Pneumatic Diversity Vents](https://github.com/BEEmod/BEE2-items/wiki/Pneumatic-Diversity-Vent) as well. Plus, this hasn't always been the case, some versions of BEEMOD haven't had this problem.

Steps I took to produce and confirm it is in this version of beemod:
1. With BEEMOD open I went to File and 'Uninstall from selected game' (Portal 2).
2. I went to steam library, portal 2 and verify integrity of game files, and waited for it to finish.
3. I opened portal 2 and ran the map editor.
4. I placed grating on a wall and a cube dropper. I placed both portals on the grating wall and could not move cube through grating.
5. I opened BEEMOD and selected portal 2.exe as my game executable.
6. I exported BEEMOD to Portal 2 and ran the game.
7. I opened the map editor again, placed grating on a wall and a cube dropper. I placed both portals on the grating wall and could then move the cube through the grating.

As I said, this also happens with the Pneumatic Diversity Vent. I can have grating on both sides of the portalable surfaces, and the cube will still be vacuumed through it. In fact, I can straight-up have a force deflection field over the portal-surface and cubes will still be vacuumed into it.

I have used earlier versions of BEEMOD where this hasn't been the case (BEE2.4_pr24). The vanilla Portal 2 _does_ have a glitch where a single grating on the opposite portal doesn't collide with the cube, but not where gratings on both sides don't collide with cubes.

**Comment by Luke18033** [comment]
Can confirm that this happens, and is still present in the geometry branch. The issue seems to have been introduced at some point between PR23 and 4.36.0. Take a look at [this](https://steamcommunity.com/sharedfiles/filedetails/?id=843347839) old map of mine, specifically the fourth (back-left) chamber. In it, the player is required to use a funnel to hold a cube against a grating with a portal behind it, which works fine.
![portal2_E85QFE6eaT](https://user-images.githubusercontent.com/19228201/87094567-f3d11100-c1f3-11ea-9a88-2af77c1cdd88.png)
Upon recompiling the map on the geometry branch (in Art Therapy style, though that's irrelevant), the cube passes straight through the grating without so much as even being bumped to the side.
![image](https://user-images.githubusercontent.com/19228201/87094690-2aa72700-c1f4-11ea-82a2-227d019d7b8b.png)
Comparing a decompiled version of the original map with a newly-exported copy, I noticed that the `func_clip_vphysics` is now only 2 units thick, instead of 4. Further testing indicates that this is indeed the cause of the issue, and I'm not sure why it was changed in the first place...

**Comment by TeamSpen210** [comment]
This seems to have been present ever since I reimplemented the brush generation myself to enable Glass Holes. I'll have to look at the original stuff, see how thick they were. Glass/grating is really fragile, changing anything causes something to break.

**Comment by Luke18033** [comment]
Seems to have been fixed at some point, can someone test this in 4.39.2?

**Comment by LautaroL20** [comment]
> Seems to have been fixed at some point, can someone test this in 4.39.2?

Acording to issue #3995, it would confirm that in BEEmod version 4.40.2 this is still an issue.
