### ISSUE TITLE
Antigel is missing their texture

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#3655]
![Antigel](https://user-images.githubusercontent.com/12244376/108663954-8044f100-74b0-11eb-8c1d-bdab8cf8337d.png)

**Comment by Luke18033** [comment]
Should now be fixed in 4.39.2

**Comment by HeimlichLaboratories** [comment]
Can confirm it still doesn't work. 4.39.2 with 4.39.1 packages and still missing textures

**Comment by HeimlichLaboratories** [comment]
What is it actually supposed to look like? Can anyone paste a picture or something?

**Comment by Luke18033** [comment]
Should now *actually* be fixed in 4.40.
