### ISSUE TITLE
wrong type of piston stairs in overgrown

### ISSUE THREAD

**Issue by ellingtonvengaboysmuseum** [BEEmod/BEE2-items#67]
wrong type of piston stairs in overgrown

![preview0010](https://cloud.githubusercontent.com/assets/11165643/8559958/048cb374-24e1-11e5-8618-1a09f32ad46b.jpg)

**Comment by ellingtonisland** [comment]
will be fixed eventually

**Comment by Konclan** [comment]
This is fixed now isn't it?

**Comment by TeamSpen210** [comment]
Not yet.

**Comment by Konclan** [comment]
Huh, guess I just didn't notice

**Comment by ZombiePwner1** [comment]
This is fixed.

**Comment by TeamSpen210** [comment]
It's not fixed yet actually. The tiles now change (since they use templates), but the arms are still clean.

**Comment by ZombiePwner1** [comment]
Right I didn't see the clean arms while I was play testing so didn't notice

**Comment by LautaroL20** [comment]
I tested this and both portalable and non-portalable are now styled.

**Comment by TeamSpen210** [comment]
No.it's not, the tops are but not the arms.

**Comment by LautaroL20** [comment]
Whoops, i didn´t look into that.

**Comment by TeamSpen210** [comment]
Finally implemented.
